import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex h-20 text-lg text-neutral-700 justify-end items-center">
          <Link href="/playlists" className="mx-5">Playlists</Link>
          <Link href="/" className="mx-5 sm:mr-60">Home</Link>
        </nav>
        <div className="m-5 mx-auto container">
            {children}
        </div>
        </body>
    </html>
  )
}
