import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Provider from "./provider";
import ThemeSwitcher from "./themeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b dark:from-zinc-900 dark:to-zinc-800 from-[#d3dcf5] to-[#e6e6e6]">
        <Provider>
          <nav className="flex h-20 text-lg dark:text-neutral-200 text-neutral-700 justify-end items-center">
            <Link href="/playlists" className="mx-5">
              Playlists
            </Link>
            <Link href="/" className="mx-5">
              Home
            </Link>
            <ThemeSwitcher/>
          </nav>
          <div className="m-5 mx-auto container">
            {children}
          </div>
        </Provider>
      </body>
    </html>
  );
}
